### ISSUE TITLE
Prevent validating rails templates

### ISSUE THREAD

**Issue by surajreddy** [Shopify/better-html#1]
## Problem
Templates outside the app structure (ex: rails) are being validated.

**Symptoms:**
- The email preview templates in rails that surround preview emails `rails/mailers` raise `BetterHtml::DontInterpolateHere in Rails::Mailers#preview`

## Solution
TBD

**Comment by rafaelfranca** [comment]
It was fixed here https://github.com/Shopify/better-html/commit/a93ac111367d69f008737dc20187f1f1e6c79c87. Just ignore the files you don't want to be checked.

**Comment by rjwalters** [comment]
for anybody who runs into this same issue, add an initializer:

config/initializers/better-html.rb

``` ruby
if defined?(BetterHtml)
  BetterHtml.configure do |config|
    config.template_exclusion_filter = proc { |filename|
      !filename.start_with?(Rails.root.to_s)
    }
  end
end
```
