### ISSUE TITLE
not working the partial_attribute_name_pattern setting.

### ISSUE THREAD

**Issue by toshi-ue** [Shopify/better-html#106]
I'm setting up with reference to README.md,
https://github.com/Shopify/better-html#how-to-use

but when I run the test with RSpec, the following error is displayed.
```bash
      ActionView::Template::Error:
        Invalid attribute name "class" does not match regular expression "/\\A[a-zA-Z0-9\\-\\:\\_]+\\z/"
        On line 1 column 5:
        <div class="container-fluid" id="wrapper_container">
```
I've tried several things with reference to the code in the gem's configuration file, but it doesn't work.
https://github.com/Shopify/better-html/blob/d2e117d6e6d375edfc25a664b1d04e1db7d4931f/lib/better_html/config.rb

When checking the operation of regular expressions using Rubular, my notation seems to work without problems.
![10_01_14](https://user-images.githubusercontent.com/46378023/218228729-a747df0c-f5df-4c42-a6b9-63fc4bbb4abc.jpg)

I develop with Docker.
OS: mac, BigSur
Ruby: 2.7.7
Rails: 6.1.7
erb_lint: 0.3.1
better_html: 2.0.1

My code is here.

Gemfile
```ruby
source 'https://rubygems.org'

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.7'

group :development, :test do
  gem "better_html"
  gem 'erb_lint', require: false
end
```

config/initializers/better_html.rb
```ruby
BetterHtml.config = BetterHtml::Config.new(YAML.load(File.read("#{Rails.root}/.better-html.yml")))
```

.better-html
```bash
---
allow_single_quoted_attributes: true
allow_unquoted_attributes: false
partial_attribute_name_pattern: /\A[a-zA-Z0-9\-\:\_]+\z/
# pending
# partial_tag_name_pattern: /\A[a-z0-9\-\:\_]+\z/
```

Please let me know why it doesn't work and how to fix it.
thank you.

**Comment by rafaelfranca** [comment]
Your regular expresson is being escaped. Try to set it using Ruby instead of yml

**Comment by thejonroberts** [comment]
I ran into the same issue, trying to consolidate my settings with [erb-lint](https://github.com/Shopify/erb-lint#configuration). The problem is that the pattern was being loaded as a String rather than Regexp.

First off, You have to format the yaml value correctly to be read as a Regexp:
```yml
partial_tag_name_pattern: !ruby/regexp /\A[a-z0-9\-\:]+\z/
```
Also, YAML/psych will not load regexp by default after the `safe_load` change in psych v4. You have two options in the initializer:
```ruby
yaml_config = YAML.load_file file_path, permitted_classes: [Regexp]
# OR
yaml_config = YAML.unsafe_load_file file_path
```
If the file is yours, the unsafe_load is fine to use!

Here is my final initializer file for reference:
```ruby
# config/initializers/better_html.rb

file_path = Rails.root.join(".better-html.yml")
yaml_config = YAML.load_file file_path, permitted_classes: [Regexp], symbolize_names: true
BetterHtml.config = BetterHtml::Config.new(yaml_config)

BetterHtml.configure do |config|
  # exclude templates provided by gem libraries
  config.template_exclusion_filter = proc { |filename| !filename.start_with?(Rails.root.to_s) }
end
```

I can put up a README change PR sometime soon if and get it documented.

**Comment by thejonroberts** [comment]
I have signed the CLA!
