### ISSUE TITLE
html_attributes for adding extra values?

### ISSUE THREAD

**Issue by phantomwhale** [Shopify/better-html#117]
Is there something available in better html to make this line more elegant / DRY, whilst still passing the default ERB compilation checks?

```ruby
<div
   <%= some_condition? ? html_attributes(class: "foo bar ") : html_attributes(class: "foo") %>>
</div>
```

Note - previously this code was 

```ruby
<div class="foo <% if some_condition? %>bar<% end %>">
``` 

Obviously this didn't pass the checks!

**Comment by jherdman** [comment]
I've been using the [`tag` helper](https://api.rubyonrails.org/classes/ActionView/Helpers/TagHelper.html#method-i-tag) sort of like this:

```erb
<%= tag.div(class: some_condition? "foo bar" : "foo") do %>
  Hello, world.
<% end %>
```

I know it's not quite what you're after though. Maybe https://github.com/mikker/classnames is more up your alley?

**Comment by rafaelfranca** [comment]
You want this helper https://api.rubyonrails.org/classes/ActionView/Helpers/TagHelper.html#method-i-class_names
