### ISSUE TITLE
Rails 6.0.0. alpha - Deprecation warning

### ISSUE THREAD

**Issue by ccasabona** [Shopify/better-html#42]
Receiving this notice in the Rails 6 alpha log:

DEPRECATION WARNING: escape_whitelist is deprecated and will be removed from Rails 6.1 (use #escape_ignore_list instead) (called from generate at /Users/user/.rvm/gems/ruby-2.6.0@ruby260rails6alpha/gems/better_html-1.0.11/lib/better_html/better_erb.rb:61)

Rails 6.0.0 alpha, Ruby 2.6.0

**Comment by douglas** [comment]
Same problem is ServicesDB as well.

**Comment by clayton-shopify** [comment]
This was fixed in https://github.com/Shopify/better-html/pull/46.
