### ISSUE TITLE
Recommendations for conditional boolean attributes?

### ISSUE THREAD

**Issue by muan** [Shopify/better-html#44]
I am curious how do people write boolean attributes with the existing recommendations? Is there a way to write them in a way that is parsed into the AST?

For something like this

```erb
<button <% unless editable? %>disabled<% end %>>Edit</button>
```

it gives us attribute name `disabled<% end %>` with empty attribute value. 

And `html_attributes`

```erb
<button <%= html_attributes(disabled: editable?) %>>Edit</button>
<button <%= html_attributes(disabled: true) if editable? %>>Edit</button>
```

doesn't actually gets parsed as attributes. 

This markup doesn't work for boolean attributes for obvious reasons.

```erb
<button disabled="<%= editable? %>"></button>
```

🤔 

Thanks!

**Comment by clayton-shopify** [comment]
I believe this will produce the expected result:
```html
<button <%= html_attributes(disabled: 'disabled') if editable? %>>Edit</button>
```
