### ISSUE TITLE
Unavoidable error on inline SVG element <clipPath>

### ISSUE THREAD

**Issue by Johnkinging** [Shopify/better-html#53]
I just installed better-html on https://github.com/Shopify/downrigger but I'm getting two errors (the same error from each recommended test:

```
ActionView::Template::Error: Invalid tag name "clipPath" does not match regular expression /\A[a-z0-9\-\:]+\z/
On line 129 column 8:
                                                        <clipPath id="border-clip">
        ^^^^^^^^
    test/controllers/ui_controller_test.rb:6:in `block in <class:UiControllerTest>'
```

https://github.com/Shopify/downrigger/blob/master/app/views/ui/show.html.erb#L129

I get why it's throwing the error, but other than this test I have no reason to _not_ have this as inline image code, since it allows for better CSS manipulation, which is a key aspect to the design.

The tag itself is to spec:

https://www.w3.org/TR/SVG11/masking.html#EstablishingANewClippingPath

I'm unfamiliar with better-html, are there any ignore rules I can put in place anywhere?

**Comment by Johnkinging** [comment]
Oh it's the hyphen, whoops

**Comment by richter-alex** [comment]
@Johnkinging You can add capital letters to this regex, resolving the issue:

```rb
# config/initializers/better_html.rb

BetterHtml.configure do |config|
  config.partial_tag_name_pattern = /\A[a-zA-Z0-9\-\:]+\z/
end
```

**Comment by Johnkinging** [comment]
That should do the trick, thanks Alex!
