### ISSUE TITLE
Add support for annotate_template_file_names

### ISSUE THREAD

**Issue by bricesanchez** [Shopify/better-html#76]
Rails 6.1 recently introduce the configuration `config.action_view.annotate_template_file_names` in this PR: https://github.com/rails/rails/pull/38848

I'm not able to see the comments in the HTML until i've removed the better_html gem.

Could you add the support for this new configuration?

**Comment by jpcody** [comment]
I know it's been a couple of years, but after recently installing `better_html`, I've noticed these comments were removed from the DOM in our application. In case it's any help or inspiration, this is [the HAML implementation](https://github.com/haml/haml/pull/1050) of the same feature. If it's not a priority at Shopify, I could possibly take a stab in the future.

**Comment by iainbeeston** [comment]
To help anyone else trying to find this, the config variable in action view is called [`annotate_rendered_view_with_filenames`](https://guides.rubyonrails.org/configuring.html#config-action-view-annotate-rendered-view-with-filenames)

**Comment by iainbeeston** [comment]
I've added support for this in #122 122

**Comment by iainbeeston** [comment]
@rafaelfranca I think this should be closed now that #122 is merged?
